name: Build, Store, and Deploy Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: TestingFolder/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy Project

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: ./downloaded/

    - name: Install Databricks CLI
      run: pip install databricks-cli

    - name: Set environment variables
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
        echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}" >> $GITHUB_ENV

    - name: Set up Databricks CLI
      uses: databricks/setup-cli@main

    - name: Deploy to Databricks
      run: |
        databricks workspace import /downloaded/
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
